apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-advanced
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 30s}
        - setWeight: 50
        - pause: {duration: 1m}
        - setWeight: 100
  selector:
    matchLabels:
      app: nginx-advanced
  template:
    metadata:
      labels:
        app: nginx-advanced
    spec:
      containers:
      - name: nginx
        image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/quay.io/argoproj/argo-rollouts:v1.8.2
        ports:
        - containerPort: 80
