apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-server
  template:
    metadata:
      labels:
        app: message-server
    spec:
      containers:
      - name: message-server
        image: 192.168.2.92/jenkins/message-server:122
        imagePullPolicy: Always
        ports:
        - containerPort: 22339
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      imagePullSecrets:
      - name: harbor-secret  # 必须提前创建

---
apiVersion: v1
kind: Service
metadata:
  name: message-server-service
spec:
  type: NodePort
  selector:
    app: message-server
  ports:
  - protocol: TCP
    port: 22339
    targetPort: 22339
    nodePort: 22339
